<a href="https://colab.research.google.com/github/vikassinngh123/AI-ML-Learning/blob/main/06-Deep-Learning/01-PyTorch/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.11.0+cu128
True


In [2]:
scaler=torch.tensor(2)

In [3]:
print(f"the no of dimension of scaler {scaler.ndim}")
print(f"geting the tensor out as python int {scaler.item()}")

the no of dimension of scaler 0
geting the tensor out as python int 2


In [4]:
vector=torch.tensor([2,3])
vector

tensor([2, 3])

In [5]:
print(f"the ndim of vector {vector.ndim}")
print(f"the shape of vector {vector.shape}")

the ndim of vector 1
the shape of vector torch.Size([2])


In [6]:
matrix=torch.tensor([[3,4],
                    [7,6]])
matrix

tensor([[3, 4],
        [7, 6]])

In [7]:
print(f"ndim of this matrix is {matrix.ndim}")
print(f"shape of matrix {matrix.shape}")

ndim of this matrix is 2
shape of matrix torch.Size([2, 2])


In [8]:
tensor=torch.tensor([[[1,2,3],
                    [4,5,6],
                    [7,8,9],
                    [3,5,6]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9],
         [3, 5, 6]]])

In [9]:
tensor.shape

torch.Size([1, 4, 3])

In [10]:
tensor.ndim

3

### Random Tensor

In [11]:
random_tensor=torch.rand(2,3,5)
random_tensor

tensor([[[0.0136, 0.1172, 0.9918, 0.2054, 0.2925],
         [0.3559, 0.7950, 0.0527, 0.8386, 0.6870],
         [0.3850, 0.2484, 0.2602, 0.2503, 0.7950]],

        [[0.2859, 0.4943, 0.3992, 0.1951, 0.8233],
         [0.1905, 0.5107, 0.6876, 0.0293, 0.5280],
         [0.6173, 0.8587, 0.1115, 0.6570, 0.1601]]])

In [12]:
print(f"Shape {random_tensor.shape}")
print(f"ndim {random_tensor.ndim}")
print(f"dtype {random_tensor.dtype}")
print(f"device {random_tensor.device}")

Shape torch.Size([2, 3, 5])
ndim 3
dtype torch.float32
device cpu


In [13]:
random_image_tensor=torch.rand(3,224,224) # color channels(R,G,B) , height , weight
print(f"Shape-> {random_image_tensor.shape}")
print(f"ndim-> {random_image_tensor.ndim}")
print(f"dtype-> {random_image_tensor.dtype}")
print(f"device-> {random_image_tensor.device}")

Shape-> torch.Size([3, 224, 224])
ndim-> 3
dtype-> torch.float32
device-> cpu


### Zeroes and Ones tensor

In [14]:
zeroes=torch.zeros(2,3,3)
zeroes

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [15]:
ones=torch.ones(size=(2,3,3))
print(ones)
print(f"\nShape-> {ones.shape}")
print(f"ndim-> {ones.ndim}")
print(f"dtype-> {ones.dtype}")

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

Shape-> torch.Size([2, 3, 3])
ndim-> 3
dtype-> torch.float32


In [16]:
ones_int=ones.type(torch.int32)
print(ones_int)
print(f"\nShape-> {ones_int.shape}")
print(f"ndim-> {ones_int.ndim}")
print(f"dtype-> {ones_int.dtype}")

tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]], dtype=torch.int32)

Shape-> torch.Size([2, 3, 3])
ndim-> 3
dtype-> torch.int32


### tensor range and tensor likes...

In [17]:
range=torch.arange(start=0,end=101,step=5)
range

tensor([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
         70,  75,  80,  85,  90,  95, 100])

In [18]:
zeros_likes_range=torch.zeros_like(input=range)
zeros_likes_range

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Operations

In [19]:
f1=torch.tensor([1,2,3])
f2=torch.tensor([5,3,7])

In [20]:
add=f1+f2
multi=f1*f2
sub=f1-f2
div=f1/f2
print(f"add-> {add}")
print(f"multi-> {multi}")
print(f"sub-> {sub}")
print(f"div-> {div}")
print(f"Matrix Multipication -> {f1.matmul(f2)}")

add-> tensor([ 6,  5, 10])
multi-> tensor([ 5,  6, 21])
sub-> tensor([-4, -1, -4])
div-> tensor([0.2000, 0.6667, 0.4286])
Matrix Multipication -> 32


In [21]:
tensor=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [22]:
print(f"add a single number to tensor->\n {tensor+10}")
print(f"multi a single number to tensor->\n {tensor*10}")
print(f"sub a single number to tensor->\n {tensor-10}")
print(f"div a single number to tensor->\n {tensor/10}")

add a single number to tensor->
 tensor([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])
multi a single number to tensor->
 tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
sub a single number to tensor->
 tensor([[-9, -8, -7],
        [-6, -5, -4],
        [-3, -2, -1]])
div a single number to tensor->
 tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000],
        [0.7000, 0.8000, 0.9000]])


In [23]:
print(f"Matrix Multipication of tensor->\n {tensor.mm(tensor)}")

Matrix Multipication of tensor->
 tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])


### Tensor **transpose** (for changing shape)

In [24]:
t_A=torch.tensor([[1,2],
                  [3,4],
                  [5,6]])
t_B=torch.tensor([[7,8],
                  [9,10],
                  [11,12]])

In [25]:
print("t_A.matmul(t_B) will give an error since it does not follow matrix multipication rule\n")

try:
    t_A.mm(t_B)
except:
  print("RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)")

t_A.matmul(t_B) will give an error since it does not follow matrix multipication rule

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)


In [26]:
t_B.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [27]:
print(f"Orignal shapes of t_B-> {t_B.shape}\n")
print(f"Transposed shapes of t_B-> {t_B.T.shape}")

Orignal shapes of t_B-> torch.Size([3, 2])

Transposed shapes of t_B-> torch.Size([2, 3])


In [28]:
print(f"matrix multipication of t_A and t_B transpose\n {t_A.mm(t_B.T)}\n")

print(f"matrix multipication of t_A transpose and t_B\n {t_A.T.mm(t_B)}")

matrix multipication of t_A and t_B transpose
 tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

matrix multipication of t_A transpose and t_B
 tensor([[ 89,  98],
        [116, 128]])


### Tensor Aggregration

In [29]:
ten_1=torch.tensor([[12,54,23],
                [1,8,94],
                [34,56,21]])
ten_1

tensor([[12, 54, 23],
        [ 1,  8, 94],
        [34, 56, 21]])

In [30]:
print(f"max of tensor-> {ten_1.max()}\n")
print(f"min of tensor-> {ten_1.min()}\n")
print(f"mean of tensor-> {ten_1.type(torch.float32).mean()}\n")
print(f"sum of tensor-> {ten_1.sum()}\n")

max of tensor-> 94

min of tensor-> 1

mean of tensor-> 33.66666793823242

sum of tensor-> 303



#### Positional min and max

In [31]:
print(f"max of tensor position-> {ten_1.argmax()}\n")
print(f"min of tensor position-> {ten_1.argmin()}\n")

max of tensor position-> 5

min of tensor position-> 3



In [32]:
# When we call argmax() without specifying a dimension (dim),
# PyTorch flattens the tensor into a 1D sequence to find the position:
# Index 0: 12
# Index 1: 54
# Index 2: 23
# Index 3: 1
# Index 4: 8
# Index 5: 94 -> (Maximum Value)
# Index 6: 34
# Index 7: 56
# Index 8: 21
# Since 94 is the largest element and sits at index 5, ten_1.argmax() gives 5.

In [33]:
ten_1[(1,2)]

tensor(94)

### Reshaping , Stacking , Squeezing and Unsqueezing

In [34]:
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [35]:
x_reshaped1=x.reshape(1,9)
x_reshaped1,x_reshaped1.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [36]:
x_reshaped2=x.reshape(9,1)
x_reshaped2,x_reshaped2.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [37]:
x_reshaped3=x.reshape(3,3)
x_reshaped3,x_reshaped3.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [38]:
# View
y=x.view(1,9)
y,y.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [39]:
y[:,2]=34
y,x

(tensor([[ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [40]:
# Stacking tensors

x_stacked0=torch.stack([x,x,x,x],dim=0)
x_stacked0

tensor([[ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [41]:
x_stacked1=torch.stack([x,x,x,x],dim=1)
x_stacked1

tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [34., 34., 34., 34.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.]])

In [42]:
# squeeze and unsqueeze
x_unsqueeze0=x_stacked0.unsqueeze(dim=0)
x_unsqueeze1=x_stacked0.unsqueeze(dim=1)
x_unsqueeze2=x_stacked0.unsqueeze(dim=2)
print(f"{x_unsqueeze0} \n shape of this unsqueeze tensor {x_unsqueeze0.shape}\n")
print(f"{x_unsqueeze1} \n shape of this unsqueeze tensor {x_unsqueeze0.shape}\n")
print(f"{x_unsqueeze2} \n shape of this unsqueeze tensor {x_unsqueeze0.shape}\n")

tensor([[[ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.],
         [ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.],
         [ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.],
         [ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.]]]) 
 shape of this unsqueeze tensor torch.Size([1, 4, 9])

tensor([[[ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.]],

        [[ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.]],

        [[ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.]],

        [[ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.]]]) 
 shape of this unsqueeze tensor torch.Size([1, 4, 9])

tensor([[[ 1.],
         [ 2.],
         [34.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.]],

        [[ 1.],
         [ 2.],
         [34.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.]],

        [[ 1.],
         [ 2.],
         [34.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [

In [43]:
x_squeeze0=x_unsqueeze0.squeeze(dim=0)
x_squeeze1=x_unsqueeze1.squeeze(dim=1)
x_squeeze2=x_unsqueeze2.squeeze(dim=2)
print(f"shape of this squeeze0 tensor {x_squeeze0.shape}\n")
print(f"shape of this squeeze1 tensor {x_squeeze1.shape}\n")
print(f"shape of this squeeze2 tensor {x_squeeze2.shape}\n")

print(f"all the squeeze tensor of unsqueeze tensor just remove the dim that was added and x_squeeze0/1/2 are all same \n\n{x_squeeze0}")

shape of this squeeze0 tensor torch.Size([4, 9])

shape of this squeeze1 tensor torch.Size([4, 9])

shape of this squeeze2 tensor torch.Size([4, 9])

all the squeeze tensor of unsqueeze tensor just remove the dim that was added and x_squeeze0/1/2 are all same 

tensor([[ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.]])


In [44]:
### Permute

per=torch.randn(2,4,6) # 0->2 , 1->4 ,2->6 by using permute we can change the order of it
per.size()

torch.Size([2, 4, 6])

In [45]:
torch.permute(per,(2,0,1)).size()

torch.Size([6, 2, 4])

In [46]:
torch.permute(per,(1,0,2)).size()

torch.Size([4, 2, 6])

### Indexing

In [47]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [48]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [49]:
x[0][0]

tensor([1, 2, 3])

In [50]:
x[0][1]

tensor([4, 5, 6])

In [51]:
x[0][0][0]

tensor(1)

In [52]:
x[0][1][1]

tensor(5)

In [53]:
# use : for selecting all of a targeted dimension
x[:,0]

tensor([[1, 2, 3]])

In [54]:
# All the values of 0th and 1st dim but only index 1 of 2nd dim
x[:, :, 1]

tensor([[2, 5, 8]])

### Numpy to Pytorch Tensors

In [55]:
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
print(f"array-> {array}\n")
print(f"tensor-> {tensor}\n")

array-> [1. 2. 3. 4. 5. 6. 7.]

tensor-> tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)



In [56]:
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [57]:
# tensor to numpy
ten=torch.arange(1,9)
numpy_tensor=ten.numpy()
print(f"tensor-> {ten}\n")
print(f"numpy_tensor-> {numpy_tensor}\n")

tensor-> tensor([1, 2, 3, 4, 5, 6, 7, 8])

numpy_tensor-> [1 2 3 4 5 6 7 8]



#### Using manual seed for less randomness
* Also so that the random tensor does not change every time i run that cell

In [58]:
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)
print(f"random_tensor_A-> \n{random_tensor_A}\n")
print(f"random_tensor_B-> \n{random_tensor_B}\n")

random_tensor_A-> 
tensor([[0.4348, 0.6578, 0.7170, 0.1988],
        [0.1013, 0.3327, 0.8589, 0.6408],
        [0.8624, 0.7117, 0.7163, 0.8618]])

random_tensor_B-> 
tensor([[0.2059, 0.2487, 0.1273, 0.5042],
        [0.4684, 0.9530, 0.7628, 0.6755],
        [0.9829, 0.7234, 0.2379, 0.2490]])



In [59]:
torch.manual_seed(42)
random_tensor_A=torch.rand(3,4)

torch.manual_seed(42)
random_tensor_B=torch.rand(3,4)
print(f"random_tensor_A-> \n{random_tensor_A}\n")
print(f"random_tensor_B-> \n{random_tensor_B}\n")

random_tensor_A-> 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

random_tensor_B-> 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

