<a href="https://colab.research.google.com/github/vikassinngh123/AI-ML-Learning/blob/main/06-Deep-Learning/01-PyTorch/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.11.0+cu128
True


In [2]:
scaler=torch.tensor(2)

In [3]:
print(f"the no of dimension of scaler {scaler.ndim}")
print(f"geting the tensor out as python int {scaler.item()}")

the no of dimension of scaler 0
geting the tensor out as python int 2


In [4]:
vector=torch.tensor([2,3])
vector

tensor([2, 3])

In [5]:
print(f"the ndim of vector {vector.ndim}")
print(f"the shape of vector {vector.shape}")

the ndim of vector 1
the shape of vector torch.Size([2])


In [6]:
matrix=torch.tensor([[3,4],
                    [7,6]])
matrix

tensor([[3, 4],
        [7, 6]])

In [7]:
print(f"ndim of this matrix is {matrix.ndim}")
print(f"shape of matrix {matrix.shape}")

ndim of this matrix is 2
shape of matrix torch.Size([2, 2])


In [8]:
tensor=torch.tensor([[[1,2,3],
                    [4,5,6],
                    [7,8,9],
                    [3,5,6]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9],
         [3, 5, 6]]])

In [9]:
tensor.shape

torch.Size([1, 4, 3])

In [10]:
tensor.ndim

3

### Random Tensor

In [11]:
random_tensor=torch.rand(2,3,5)
random_tensor

tensor([[[0.4969, 0.9729, 0.6052, 0.6881, 0.0339],
         [0.9519, 0.3087, 0.3828, 0.3853, 0.7807],
         [0.4256, 0.0050, 0.1050, 0.9298, 0.4838]],

        [[0.1670, 0.9993, 0.2043, 0.0576, 0.2190],
         [0.4663, 0.7756, 0.3779, 0.9236, 0.6760],
         [0.9533, 0.4983, 0.3956, 0.0658, 0.8253]]])

In [12]:
print(f"Shape {random_tensor.shape}")
print(f"ndim {random_tensor.ndim}")
print(f"dtype {random_tensor.dtype}")
print(f"device {random_tensor.device}")

Shape torch.Size([2, 3, 5])
ndim 3
dtype torch.float32
device cpu


In [13]:
random_image_tensor=torch.rand(3,224,224) # color channels(R,G,B) , height , weight
print(f"Shape-> {random_image_tensor.shape}")
print(f"ndim-> {random_image_tensor.ndim}")
print(f"dtype-> {random_image_tensor.dtype}")
print(f"device-> {random_image_tensor.device}")

Shape-> torch.Size([3, 224, 224])
ndim-> 3
dtype-> torch.float32
device-> cpu


### Zeroes and Ones tensor

In [14]:
zeroes=torch.zeros(2,3,3)
zeroes

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [15]:
ones=torch.ones(size=(2,3,3))
print(ones)
print(f"\nShape-> {ones.shape}")
print(f"ndim-> {ones.ndim}")
print(f"dtype-> {ones.dtype}")

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

Shape-> torch.Size([2, 3, 3])
ndim-> 3
dtype-> torch.float32


In [16]:
ones_int=ones.type(torch.int32)
print(ones_int)
print(f"\nShape-> {ones_int.shape}")
print(f"ndim-> {ones_int.ndim}")
print(f"dtype-> {ones_int.dtype}")

tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]], dtype=torch.int32)

Shape-> torch.Size([2, 3, 3])
ndim-> 3
dtype-> torch.int32


### tensor range and tensor likes...

In [17]:
range=torch.arange(start=0,end=101,step=5)
range

tensor([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
         70,  75,  80,  85,  90,  95, 100])

In [18]:
zeros_likes_range=torch.zeros_like(input=range)
zeros_likes_range

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Operations

In [19]:
f1=torch.tensor([1,2,3])
f2=torch.tensor([5,3,7])

In [20]:
add=f1+f2
multi=f1*f2
sub=f1-f2
div=f1/f2
print(f"add-> {add}")
print(f"multi-> {multi}")
print(f"sub-> {sub}")
print(f"div-> {div}")
print(f"Matrix Multipication -> {f1.matmul(f2)}")

add-> tensor([ 6,  5, 10])
multi-> tensor([ 5,  6, 21])
sub-> tensor([-4, -1, -4])
div-> tensor([0.2000, 0.6667, 0.4286])
Matrix Multipication -> 32


In [21]:
tensor=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [22]:
print(f"add a single number to tensor->\n {tensor+10}")
print(f"multi a single number to tensor->\n {tensor*10}")
print(f"sub a single number to tensor->\n {tensor-10}")
print(f"div a single number to tensor->\n {tensor/10}")

add a single number to tensor->
 tensor([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])
multi a single number to tensor->
 tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
sub a single number to tensor->
 tensor([[-9, -8, -7],
        [-6, -5, -4],
        [-3, -2, -1]])
div a single number to tensor->
 tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000],
        [0.7000, 0.8000, 0.9000]])


In [23]:
print(f"Matrix Multipication of tensor->\n {tensor.mm(tensor)}")

Matrix Multipication of tensor->
 tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])


### Tensor **transpose** (for changing shape)

In [24]:
t_A=torch.tensor([[1,2],
                  [3,4],
                  [5,6]])
t_B=torch.tensor([[7,8],
                  [9,10],
                  [11,12]])

In [25]:
print("t_A.matmul(t_B) will give an error since it does not follow matrix multipication rule\n")

try:
    t_A.mm(t_B)
except:
  print("RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)")

t_A.matmul(t_B) will give an error since it does not follow matrix multipication rule

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)


In [26]:
t_B.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [27]:
print(f"Orignal shapes of t_B-> {t_B.shape}\n")
print(f"Transposed shapes of t_B-> {t_B.T.shape}")

Orignal shapes of t_B-> torch.Size([3, 2])

Transposed shapes of t_B-> torch.Size([2, 3])


In [28]:
print(f"matrix multipication of t_A and t_B transpose\n {t_A.mm(t_B.T)}\n")

print(f"matrix multipication of t_A transpose and t_B\n {t_A.T.mm(t_B)}")

matrix multipication of t_A and t_B transpose
 tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

matrix multipication of t_A transpose and t_B
 tensor([[ 89,  98],
        [116, 128]])


### Tensor Aggregration

In [29]:
ten_1=torch.tensor([[12,54,23],
                [1,8,94],
                [34,56,21]])
ten_1

tensor([[12, 54, 23],
        [ 1,  8, 94],
        [34, 56, 21]])

In [30]:
print(f"max of tensor-> {ten_1.max()}\n")
print(f"min of tensor-> {ten_1.min()}\n")
print(f"mean of tensor-> {ten_1.type(torch.float32).mean()}\n")
print(f"sum of tensor-> {ten_1.sum()}\n")

max of tensor-> 94

min of tensor-> 1

mean of tensor-> 33.66666793823242

sum of tensor-> 303



#### Positional min and max

In [31]:
print(f"max of tensor position-> {ten_1.argmax()}\n")
print(f"min of tensor position-> {ten_1.argmin()}\n")

max of tensor position-> 5

min of tensor position-> 3



In [32]:
# When we call argmax() without specifying a dimension (dim),
# PyTorch flattens the tensor into a 1D sequence to find the position:
# Index 0: 12
# Index 1: 54
# Index 2: 23
# Index 3: 1
# Index 4: 8
# Index 5: 94 -> (Maximum Value)
# Index 6: 34
# Index 7: 56
# Index 8: 21
# Since 94 is the largest element and sits at index 5, ten_1.argmax() gives 5.

In [33]:
ten_1[(1,2)]

tensor(94)

### Reshaping , Stacking , Squeezing and Unsqueezing

In [34]:
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [35]:
x_reshaped1=x.reshape(1,9)
x_reshaped1,x_reshaped1.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [36]:
x_reshaped2=x.reshape(9,1)
x_reshaped2,x_reshaped2.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [37]:
x_reshaped3=x.reshape(3,3)
x_reshaped3,x_reshaped3.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [38]:
# View
y=x.view(1,9)
y,y.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [39]:
y[:,2]=34
y,x

(tensor([[ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [40]:
# Stacking tensors

x_stacked0=torch.stack([x,x,x,x],dim=0)
x_stacked0

tensor([[ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [41]:
x_stacked1=torch.stack([x,x,x,x],dim=1)
x_stacked1

tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [34., 34., 34., 34.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.]])

In [42]:
# squeeze and unsqueeze
x_unsqueeze0=x_stacked0.unsqueeze(dim=0)
x_unsqueeze1=x_stacked0.unsqueeze(dim=1)
x_unsqueeze2=x_stacked0.unsqueeze(dim=2)
print(f"{x_unsqueeze0} \n shape of this unsqueeze tensor {x_unsqueeze0.shape}\n")
print(f"{x_unsqueeze1} \n shape of this unsqueeze tensor {x_unsqueeze0.shape}\n")
print(f"{x_unsqueeze2} \n shape of this unsqueeze tensor {x_unsqueeze0.shape}\n")

tensor([[[ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.],
         [ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.],
         [ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.],
         [ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.]]]) 
 shape of this unsqueeze tensor torch.Size([1, 4, 9])

tensor([[[ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.]],

        [[ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.]],

        [[ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.]],

        [[ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.]]]) 
 shape of this unsqueeze tensor torch.Size([1, 4, 9])

tensor([[[ 1.],
         [ 2.],
         [34.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.]],

        [[ 1.],
         [ 2.],
         [34.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.]],

        [[ 1.],
         [ 2.],
         [34.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [

In [43]:
x_squeeze0=x_unsqueeze0.squeeze(dim=0)
x_squeeze1=x_unsqueeze1.squeeze(dim=1)
x_squeeze2=x_unsqueeze2.squeeze(dim=2)
print(f"shape of this squeeze0 tensor {x_squeeze0.shape}\n")
print(f"shape of this squeeze1 tensor {x_squeeze1.shape}\n")
print(f"shape of this squeeze2 tensor {x_squeeze2.shape}\n")

print(f"all the squeeze tensor of unsqueeze tensor just remove the dim that was added and x_squeeze0/1/2 are all same \n\n{x_squeeze0}")

shape of this squeeze0 tensor torch.Size([4, 9])

shape of this squeeze1 tensor torch.Size([4, 9])

shape of this squeeze2 tensor torch.Size([4, 9])

all the squeeze tensor of unsqueeze tensor just remove the dim that was added and x_squeeze0/1/2 are all same 

tensor([[ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 1.,  2., 34.,  4.,  5.,  6.,  7.,  8.,  9.]])
