<a href="https://colab.research.google.com/github/vikassinngh123/AI-ML-Learning/blob/main/06-Deep-Learning/01-PyTorch/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.11.0+cu128
True


In [2]:
scaler=torch.tensor(2)

In [3]:
print(f"the no of dimension of scaler {scaler.ndim}")
print(f"geting the tensor out as python int {scaler.item()}")

the no of dimension of scaler 0
geting the tensor out as python int 2


In [4]:
vector=torch.tensor([2,3])
vector

tensor([2, 3])

In [5]:
print(f"the ndim of vector {vector.ndim}")
print(f"the shape of vector {vector.shape}")

the ndim of vector 1
the shape of vector torch.Size([2])


In [6]:
matrix=torch.tensor([[3,4],
                    [7,6]])
matrix

tensor([[3, 4],
        [7, 6]])

In [7]:
print(f"ndim of this matrix is {matrix.ndim}")
print(f"shape of matrix {matrix.shape}")

ndim of this matrix is 2
shape of matrix torch.Size([2, 2])


In [8]:
tensor=torch.tensor([[[1,2,3],
                    [4,5,6],
                    [7,8,9],
                    [3,5,6]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9],
         [3, 5, 6]]])

In [9]:
tensor.shape

torch.Size([1, 4, 3])

In [10]:
tensor.ndim

3