<a href="https://colab.research.google.com/github/vikassinngh123/AI-ML-Learning/blob/main/06-Deep-Learning/01-PyTorch/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.11.0+cu128
True


In [2]:
scaler=torch.tensor(2)

In [3]:
print(f"the no of dimension of scaler {scaler.ndim}")
print(f"geting the tensor out as python int {scaler.item()}")

the no of dimension of scaler 0
geting the tensor out as python int 2


In [4]:
vector=torch.tensor([2,3])
vector

tensor([2, 3])

In [5]:
print(f"the ndim of vector {vector.ndim}")
print(f"the shape of vector {vector.shape}")

the ndim of vector 1
the shape of vector torch.Size([2])


In [6]:
matrix=torch.tensor([[3,4],
                    [7,6]])
matrix

tensor([[3, 4],
        [7, 6]])

In [7]:
print(f"ndim of this matrix is {matrix.ndim}")
print(f"shape of matrix {matrix.shape}")

ndim of this matrix is 2
shape of matrix torch.Size([2, 2])


In [8]:
tensor=torch.tensor([[[1,2,3],
                    [4,5,6],
                    [7,8,9],
                    [3,5,6]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9],
         [3, 5, 6]]])

In [9]:
tensor.shape

torch.Size([1, 4, 3])

In [10]:
tensor.ndim

3

### Random Tensor

In [11]:
random_tensor=torch.rand(2,3,5)
random_tensor

tensor([[[0.4702, 0.2416, 0.2384, 0.0968, 0.1725],
         [0.9855, 0.8229, 0.1429, 0.4342, 0.7295],
         [0.8664, 0.5152, 0.4057, 0.0678, 0.8560]],

        [[0.6323, 0.4548, 0.7124, 0.6103, 0.7595],
         [0.5867, 0.3691, 0.8092, 0.2608, 0.3485],
         [0.8651, 0.7619, 0.2004, 0.4083, 0.1406]]])

In [12]:
print(f"Shape {random_tensor.shape}")
print(f"ndim {random_tensor.ndim}")
print(f"dtype {random_tensor.dtype}")
print(f"device {random_tensor.device}")

Shape torch.Size([2, 3, 5])
ndim 3
dtype torch.float32
device cpu


In [13]:
random_image_tensor=torch.rand(3,224,224) # color channels(R,G,B) , height , weight
print(f"Shape-> {random_image_tensor.shape}")
print(f"ndim-> {random_image_tensor.ndim}")
print(f"dtype-> {random_image_tensor.dtype}")
print(f"device-> {random_image_tensor.device}")

Shape-> torch.Size([3, 224, 224])
ndim-> 3
dtype-> torch.float32
device-> cpu


### Zeroes and Ones tensor

In [14]:
zeroes=torch.zeros(2,3,3)
zeroes

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [15]:
ones=torch.ones(size=(2,3,3))
print(ones)
print(f"\nShape-> {ones.shape}")
print(f"ndim-> {ones.ndim}")
print(f"dtype-> {ones.dtype}")

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

Shape-> torch.Size([2, 3, 3])
ndim-> 3
dtype-> torch.float32


In [16]:
ones_int=ones.type(torch.int32)
print(ones_int)
print(f"\nShape-> {ones_int.shape}")
print(f"ndim-> {ones_int.ndim}")
print(f"dtype-> {ones_int.dtype}")

tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]], dtype=torch.int32)

Shape-> torch.Size([2, 3, 3])
ndim-> 3
dtype-> torch.int32


### tensor range and tensor likes...

In [17]:
range=torch.arange(start=0,end=101,step=5)
range

tensor([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
         70,  75,  80,  85,  90,  95, 100])

In [18]:
zeros_likes_range=torch.zeros_like(input=range)
zeros_likes_range

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])