<a href="https://colab.research.google.com/github/vikassinngh123/AI-ML-Learning/blob/main/03-Numpy/My_Numpy_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

##### Basics Functions

In [2]:
a=np.array([1,2,3,4])
b=np.array([2.0,3.0,5.0,0])
c=np.array([1,2,3,4])
print(a*c)
print(a.ndim)

[ 1  4  9 16]
1


In [3]:
d=np.array([[3,4,5],[2,3,4],[5,6,7]])
print(d.ndim)
#Shape
print(a.shape)
print(d.shape)
e=np.array([[[1,2,3],[2,4,6]],[[3,6,7],[4,6,7]]])
print(e)
print(e.ndim)
print(e.shape)
#get type
print(a.dtype)
print(d.dtype)
print(a.itemsize)
print(e.itemsize,e.dtype)

2
(4,)
(3, 3)
[[[1 2 3]
  [2 4 6]]

 [[3 6 7]
  [4 6 7]]]
3
(2, 2, 3)
int64
int64
8
8 int64


##### Array Slicing

In [4]:

a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a[0,5])
print(a[1,5])


print(a[0,:])
print(a[1,:])
print(a[:,2])
#  x, -> specific row
# ,x  -> specific column

print(a[0,:5])
print(a[0, 1:6:2])
#  (0,)->1st row  1:6:2 -> normal string index slicing starting,ending and gaping

a[1,5]=57
print(a)
a[0,2]=67
print(a)

6
12
[1 2 3 4 5 6]
[ 7  8  9 10 11 12]
[3 9]
[1 2 3 4 5]
[2 4 6]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 57]]
[[ 1  2 67  4  5  6]
 [ 7  8  9 10 11 57]]


In [5]:
#3d ex
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(b[0,1,1])
print(b[0,:])
print(b[:,1:])

4
[[1 2]
 [3 4]]
[[[3 4]]

 [[7 8]]]


###### Array Patterns

In [6]:
a=np.ones((7,7))
b=np.full((5,5),2)
c=np.full((3,3),3)

c[1,1]=4
b[1:-1,1:-1]=c
a[1:-1,1:-1]=b
print(a)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 2. 2. 2. 2. 2. 1.]
 [1. 2. 3. 3. 3. 2. 1.]
 [1. 2. 3. 4. 3. 2. 1.]
 [1. 2. 3. 3. 3. 2. 1.]
 [1. 2. 2. 2. 2. 2. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [7]:
a=np.ones((5,5))
a[1:4,1:4]=np.zeros((3,3))
print(a)
a[1:4,1:4]=np.full((3,3),5)
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 5. 5. 5. 1.]
 [1. 5. 5. 5. 1.]
 [1. 5. 5. 5. 1.]
 [1. 1. 1. 1. 1.]]


#### Onion Matrix

In [8]:
n=int(input("enter number: "))
a=np.ones((n,n) , dtype=int)
c=0
d=1
e=n
while n>1:
    a[1+c:e-1,1+c:e-1]=d+1
    c+=1
    d+=1
    n-=2
    e-=1

print(a)



enter number: 9
[[1 1 1 1 1 1 1 1 1]
 [1 2 2 2 2 2 2 2 1]
 [1 2 3 3 3 3 3 2 1]
 [1 2 3 4 4 4 3 2 1]
 [1 2 3 4 5 4 3 2 1]
 [1 2 3 4 4 4 3 2 1]
 [1 2 3 3 3 3 3 2 1]
 [1 2 2 2 2 2 2 2 1]
 [1 1 1 1 1 1 1 1 1]]


##### Basic Maths

In [9]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [10]:
a+2

array([3, 4, 5, 6])

In [11]:
a-2

array([-1,  0,  1,  2])

In [12]:
a**2

array([ 1,  4,  9, 16])

In [13]:
x=np.sin(a)
y=np.cos([4,5,6])
z=np.tan([7,8,0])
print(x)
print(y)
print(z)

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[-0.65364362  0.28366219  0.96017029]
[ 0.87144798 -6.79971146  0.        ]


##### Linear Algebra

In [14]:
a=np.full((2,3),2,dtype=int)
print(a)

b=np.full((3,4),3,dtype=int)
print(b)

np.matmul(a,b)

[[2 2 2]
 [2 2 2]]
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


array([[18, 18, 18, 18],
       [18, 18, 18, 18]])

In [15]:
c=np.array([[1,2,3],[-1,4,-3],[2,6,0]])
np.linalg.det(c)

np.float64(-36.0)

In [16]:
stat=np.array([[1,2,3],[4,5,6]])
print(stat)

[[1 2 3]
 [4 5 6]]


In [17]:
np.min(stat)

np.int64(1)

In [18]:
np.max(stat,axis=1)

array([3, 6])

In [19]:
np.sum(stat)

np.int64(21)

In [20]:
np.sum(stat,axis=0)

array([5, 7, 9])

##### Stack

In [21]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
#sizes should be equall
np.vstack([v1,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [22]:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
h1=np.zeros((4,4),dtype=int)
h2=np.ones((4,2),dtype=int)
#rows sames
np.hstack((h1,h2))

array([[0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1]])

##### Data From Files

In [24]:
file_data=np.genfromtxt('/content/drive/MyDrive/data.txt',delimiter=',',dtype=int)
print(file_data)
file_data.reshape((7,6))

[[ 1  2  4 23 56  3 42 34 34 34  5  8 12 56]
 [ 3  6  8  3 45 25 15 14 87 13  1  2  1  8]
 [ 7  4 65 12 22 26 10  1  4  6  8  9 21 26]]


array([[ 1,  2,  4, 23, 56,  3],
       [42, 34, 34, 34,  5,  8],
       [12, 56,  3,  6,  8,  3],
       [45, 25, 15, 14, 87, 13],
       [ 1,  2,  1,  8,  7,  4],
       [65, 12, 22, 26, 10,  1],
       [ 4,  6,  8,  9, 21, 26]])

In [25]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


##### Boolean Logics

In [26]:
file_data > 10

array([[False, False, False,  True,  True, False,  True,  True,  True,
         True, False, False,  True,  True],
       [False, False, False, False,  True,  True,  True,  True,  True,
         True, False, False, False, False],
       [False, False,  True,  True,  True,  True, False, False, False,
        False, False, False,  True,  True]])

In [27]:
file_data[file_data > 10]

array([23, 56, 42, 34, 34, 34, 12, 56, 45, 25, 15, 14, 87, 13, 65, 12, 22,
       26, 21, 26])

In [28]:
np.any(file_data>20 , axis=0)

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True])

In [29]:
np.any(file_data>20 , axis=1)

array([ True,  True,  True])

##### Complex Array Slicing

In [30]:
ex=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(ex)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [31]:
ex[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [32]:
ex[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [33]:
ex[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

### Advanced Functions

In [34]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [35]:
print(np.arange(0,10,5))
print(np.arange(0,10,2.5))

[0 5]
[0.  2.5 5.  7.5]


In [36]:
col=np.array([[1],[2],[3]])
#col.shape -> (3,1)

row=np.array([10,20,30])
# row.shape -> (1,3)

Array=col+row
print(Array)

[[11 21 31]
 [12 22 32]
 [13 23 33]]
