In [ ]:
                    # import numpy as np
                    # a=np.array([1,2,3,4])
                    # b=np.array([2.0,3.0,5.0,0])
                    # c=np.array([1,2,3,4])
                    # print(a*c)
                    # print(a.ndim)
                    # d=np.array([[3,4,5],[2,3,4],[5,6,7]])
                    # print(d.ndim)
                    # print(a.shape)
                    # print(d.shape)
                    # e=np.array([[[1,2,3],[2,4,6]],[[3,6,7],[4,6,7]]])
                    # print(e)
                    # print(e.ndim)
                    # print(e.shape)
                    # #get type
                    # print(a.dtype)
                    # print(d.dtype)
                    # print(a.itemsize)
                    # print(e.itemsize,e.dtype)
                    
                    # a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
                    # print(a[0,5])
                    # print(a[1,5])
                    
                    
                    # print(a[0,:])
                    # print(a[1,:])
                    # print(a[:,2])
                    # #  x, -> specific row
                    # # ,x  -> specific column
                    
                    # print(a[0,:5])
                    # print(a[0, 1:6:2])
                    # #  (0,)->1st row  1:6:2 -> normal string index slicing starting,ending and gaping
                    
                    # a[1,5]=57
                    # print(a)
                    # a[0,2]=67
                    # print(a)
                    
                    # #3d ex
                    # b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
                    
                    # print(b[0,1,1])
                    # print(b[0,:])
                    # print(b[:,1:])

In [4]:
import numpy as np

a=np.ones((7,7))
b=np.full((5,5),2)
c=np.full((3,3),3)

c[1,1]=4
b[1:-1,1:-1]=c
a[1:-1,1:-1]=b
print(a)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 2. 2. 2. 2. 2. 1.]
 [1. 2. 3. 3. 3. 2. 1.]
 [1. 2. 3. 4. 3. 2. 1.]
 [1. 2. 3. 3. 3. 2. 1.]
 [1. 2. 2. 2. 2. 2. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [13]:
a=np.ones((5,5))
a[1:4,1:4]=np.zeros((3,3))
print(a)
a[1:4,1:4]=np.full((3,3),5)
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 5. 5. 5. 1.]
 [1. 5. 5. 5. 1.]
 [1. 5. 5. 5. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
n=int(input("enter number: "))
a=np.ones((n,n) , dtype=int)
c=0
d=1
e=n
while n>1:
    a[1+c:e-1,1+c:e-1]=d+1
    c+=1
    d+=1
    n-=2
    e-=1

print(a)



enter number:  9


[[1 1 1 1 1 1 1 1 1]
 [1 2 2 2 2 2 2 2 1]
 [1 2 3 3 3 3 3 2 1]
 [1 2 3 4 4 4 3 2 1]
 [1 2 3 4 5 4 3 2 1]
 [1 2 3 4 4 4 3 2 1]
 [1 2 3 3 3 3 3 2 1]
 [1 2 2 2 2 2 2 2 1]
 [1 1 1 1 1 1 1 1 1]]


In [21]:
# maths
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [22]:
a+2

array([3, 4, 5, 6])

In [23]:
a-2

array([-1,  0,  1,  2])

In [24]:
a**2

array([ 1,  4,  9, 16])

In [34]:
x=np.sin(a)
y=np.cos([4,5,6])
z=np.tan([7,8,0])
print(x)
print(y)
print(z)

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[-0.65364362  0.28366219  0.96017029]
[ 0.87144798 -6.79971146  0.        ]


In [36]:
a=np.full((2,3),2,dtype=int)
print(a)

b=np.full((3,4),3,dtype=int)
print(b)

np.matmul(a,b)

[[2 2 2]
 [2 2 2]]
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


array([[18, 18, 18, 18],
       [18, 18, 18, 18]])

In [38]:
c=np.array([[1,2,3],[-1,4,-3],[2,6,0]])
np.linalg.det(c)

np.float64(-36.0)

In [39]:
stat=np.array([[1,2,3],[4,5,6]])
print(stat)

[[1 2 3]
 [4 5 6]]


In [40]:
np.min(stat)

np.int32(1)

In [41]:
np.max(stat,axis=1)

array([3, 6])

In [42]:
np.sum(stat)

np.int32(21)

In [43]:
np.sum(stat,axis=0)

array([5, 7, 9])

In [44]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
#sizes should be equall
np.vstack([v1,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [47]:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
h1=np.zeros((4,4),dtype=int)
h2=np.ones((4,2),dtype=int)
#rows sames
np.hstack((h1,h2))

array([[0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1]])

In [62]:
file_data=np.genfromtxt('data.txt',delimiter=',',dtype=int)
print(file_data)
file_data.reshape((7,6))

[[ 1 15 14  8  5  5  6 63 64 25 26 28  3  5]
 [ 3  2  6  2  5  1  2  1 21 21 52  1 25 21]
 [ 2  5  4 45 12 15 16 26 28 35 69 14 78 75]]


array([[ 1, 15, 14,  8,  5,  5],
       [ 6, 63, 64, 25, 26, 28],
       [ 3,  5,  3,  2,  6,  2],
       [ 5,  1,  2,  1, 21, 21],
       [52,  1, 25, 21,  2,  5],
       [ 4, 45, 12, 15, 16, 26],
       [28, 35, 69, 14, 78, 75]])

In [63]:
file_data > 10

array([[False,  True,  True, False, False, False, False,  True,  True,
         True,  True,  True, False, False],
       [False, False, False, False, False, False, False, False,  True,
         True,  True, False,  True,  True],
       [False, False, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True]])

In [64]:
file_data[file_data > 10]

array([15, 14, 63, 64, 25, 26, 28, 21, 21, 52, 25, 21, 45, 12, 15, 16, 26,
       28, 35, 69, 14, 78, 75])

In [65]:
np.any(file_data>20 , axis=0)

array([False, False, False,  True, False, False, False,  True,  True,
        True,  True,  True,  True,  True])

In [66]:
np.any(file_data>20 , axis=1)

array([ True,  True,  True])

In [67]:
ex=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(ex)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [68]:
ex[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [78]:
ex[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [84]:
ex[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [86]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.arange()
np.linspace()
np.argmax()
np.dot()
np.std()
np.transpose()
np.concatenate()
np.flatten()
np.where()
np.clip()
np.unique()
np.isnan()

